services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      - kafka-net
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka

  consumer1:
    image: kafka-consumer
    container_name: consumer1
    environment:
      - CONSUMER_ID=1
    networks:
      - kafka-net
    depends_on:
      - kafka

  consumer2:
    image: kafka-consumer
    environment:
      - CONSUMER_ID=2
    networks:
      - kafka-net
    depends_on:
      - kafka

volumes:
  kafka_data:

networks:
  kafka-net:
    name: kafka-net
    driver: bridge
